---
title: "153projcode"
author: "Zhengyi Sui"
date: "5/4/2019"
output: html_document
---

```{r}
library(ggplot2)
library(astsa)
library(TSA)
library(forecast)
library(knitr)
library(fpp)
```


```{r}
dat1 <- read.csv("stat153_final_project/data1.csv")
dat2 <- as.ts(dat1$x)
colnames(dat1) <- c("time", "value")
value1 <- dat1$value
plot(dat1)
```

1. EDA
```{r}
summary(dat1)
ggplot(data = dat1) +
  geom_line(aes(x = time, y = value)) +
  geom_point(aes(x = time, y = value), size = 0.7) +
  scale_x_continuous(breaks = seq(0, 180, by = 20)) +
  scale_y_continuous(breaks = seq(0.8, 2.3, by = 0.15)) +
  xlab("time") +
  ylab("value") +
  ggtitle("Original trend of data 1") +
  theme_minimal()
# log transformation
bc <- boxcox(value1 ~ dat1$time) # lambda = 0, so log-trans

value_log <- log(value1)
plot(value_log, type = "l")
plot(diff(value_log), type = "l")

# try diffence

value_log_df1 <- diff(value_log)
plot(value_log_df1, type = "l")
acf2(value_log_df1)

# filter
# value1_filter <- stats::filter(value_log, filter = rep(1/5, 5), sides = 2)
# value1_filter
# plot.ts(cbind(value_log, value1_filter), plot.type = 'single', col = c('black', 'red'))
# resid1_filter <- value_log - value1_filter
# plot(resid1_filter, type = "l")
# acf2(resid1_filter)

plot(value_log_df1, type = "l")
acf2(value_log_df1)
# plot(resid1_filter, type = "l")
# acf2(resid1_filter)
# plot(diff(value_log_df1, lag = 6), type = "l")
# acf2(diff(value_log_df1, lag = 6))

```

2. Frequency analysis
```{r}
period1 <- periodogram(value_log_df1) #four dominant frequencies
freq1_4 <- sort(period1$spec, decreasing = T)[1:4]

sin1_1 <- sin(2*pi*freq1_4[1]*dat1$time)
cos1_1 <- cos(2*pi*freq1_4[1]*dat1$time)
sin1_2 <- sin(2*pi*freq1_4[2]*dat1$time)
cos1_2 <- cos(2*pi*freq1_4[2]*dat1$time)
sin1_3 <- sin(2*pi*freq1_4[3]*dat1$time)
cos1_3 <- cos(2*pi*freq1_4[3]*dat1$time)
sin1_4 <- sin(2*pi*freq1_4[4]*dat1$time)
cos1_4 <- cos(2*pi*freq1_4[4]*dat1$time)
dat1_freq <- data.frame(sin1_1, cos1_1, sin1_2, cos1_2, 
                        sin1_3, cos1_3, sin1_4, cos1_4)[-180,]
dat1_freq$value <- value_log_df1

freqmodel1_4 <- lm(value ~ ., data = dat1_freq)
summary(freqmodel1_4)

ggplot(data = dat1_freq) + 
  geom_line(aes(x = 1:179, y = value)) +
  geom_line(aes(x = 1:179, y = freqmodel1_4$coefficients[1] + rowSums(freqmodel1_4$coefficients[-1] * dat1_freq[,-9])),
            col = "red") +
  theme_bw()

```

3. SARIMA
```{r}
sarima1_1 <- sarima(value_log, 1,1,1, 1,0,1, 6, no.constant = T)
sarima1_2 <- sarima(value_log, 1,1,1, 1,0,1, 12, no.constant = T) #this
sarima1_3 <- sarima(value_log, 1,1,1, 2,0,2, 6, no.constant = T)
sarima1_4 <- sarima(value_log, 1,1,1, 2,0,2, 12, no.constant = T)
sarima1_5 <- sarima(value_log, 1,1,1, 1,1,1, 12, no.constant = T) #this
sarima1_6 <- sarima(value_log, 1,1,1, 2,1,2, 12, no.constant = T)
sarima1_7 <- sarima(value_log, 1,1,0, 1,1,1, 12, no.constant = T) #this

sarima1_5$ttable

sarima1_1$AIC
sarima1_2$AIC
sarima1_3$AIC
sarima1_4$AIC
sarima1_5$AIC
sarima1_6$AIC
sarima1_7$AIC

sarima1_1$BIC
sarima1_2$BIC
sarima1_3$BIC
sarima1_4$BIC
sarima1_5$BIC
sarima1_6$BIC
sarima1_7$BIC

plot(value_log, type = "l")
sp <- sarima.for(value_log, n.ahead = 10, 1,0,1, 1,0,1, 12)
exp(sp$pred)
```

#CV GENERIC
```{r}

CVgeneric <- function(data, k = 10, p = 1, d = 1, q = 1, P = 1, D = 1, Q = 1,
                      S = 12, noconstant = T) {
  mse <- numeric()
  
  g <- length(data) %/% k
  for (i in 3:(k - 1)) {
    train_set <- data[1:(i * g)]
    if (i == k - 1) {
      val_set <- data[(i*g):length(data)]
    } else {
      val_set <- data[(i*g):((i+1)*g)]
    }
    y_pred <- sarima.for(train_set, n.ahead = length(val_set), p, d, q, P, D, Q, S, no.constant = noconstant)
    mse <- c(mse, sum((y_pred$pred - val_set)^2))
  }
  return(mean(mse))
}

```

```{r, fig.show = "hide"}
print(CVgeneric(value_log, D = 0))
print(CVgeneric(value_log))
print(CVgeneric(value_log, q = 0))
```


```{r}
prediction1 <- sarima.for(value_log, n.ahead = 10, 1, 1, 0, 1, 1, 1, 12,
                          no.constant = T)
pred1 <- exp(prediction1$pred)
write(pred1, "D1_7_26209413_3034503655_3034503668_26657181_NA.txt", sep = ",")
```


